#include "threads/interrupt.h"
#include <debug.h>
#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>
#include "threads/flags.h"
#include "threads/intr-stubs.h"
#include "threads/io.h"
#include "threads/thread.h"
#include "threads/mmu.h"
#include "threads/vaddr.h"
#include "devices/timer.h"
#include "intrinsic.h"
#ifdef USERPROG
#include "userprog/gdt.h"
#endif

/* Number of x86_64 interrupts. */
/* x86_64에서의 인터럽트 개수. */
#define INTR_CNT 256

/* Creates an gate that invokes FUNCTION.

   The gate has descriptor privilege level DPL, meaning that it
   can be invoked intentionally when the processor is in the DPL
   or lower-numbered ring.  In practice, DPL==3 allows user mode
   to call into the gate and DPL==0 prevents such calls.  Faults
   and exceptions that occur in user mode still cause gates with
   DPL==0 to be invoked.

   TYPE must be either 14 (for an interrupt gate) or 15 (for a
   trap gate).  The difference is that entering an interrupt gate
   disables interrupts, but entering a trap gate does not.  See
   [IA32-v3a] section 5.12.1.2 "Flag Usage By Exception- or
   Interrupt-Handler Procedure" for discussion. */
/* FUNCTION을 호출하는 게이트를 생성한다.

   게이트는 DPL(Descriptor Privilege Level)을 가지며, 이는 CPU가 해당 DPL
   또는 더 낮은 링에 있을 때 의도적으로 호출될 수 있음을 의미한다.
   실제로 DPL==3이면 유저 모드에서 호출 가능하고, DPL==0이면 그러한 호출을
   막는다. 다만 유저 모드에서 발생한 fault/exception은 여전히 DPL==0 게이트를
   통해 처리된다.

   TYPE은 14(인터럽트 게이트) 또는 15(트랩 게이트)여야 한다.
   차이는 인터럽트 게이트로 진입하면 인터럽트가 비활성화되지만, 트랩 게이트로
   진입하면 비활성화되지 않는다는 점이다. 자세한 내용은
   [IA32-v3a] 5.12.1.2 "Flag Usage By Exception- or Interrupt-Handler Procedure"
   를 참고. */

struct gate {
	unsigned off_15_0 : 16;   // low 16 bits of offset in segment
	/* 세그먼트 내 오프셋의 하위 16비트 */
	unsigned ss : 16;         // segment selector
	/* 세그먼트 셀렉터 */
	unsigned ist : 3;        // # args, 0 for interrupt/trap gates
	/* IST 인덱스(인터럽트/트랩 게이트에서는 보통 0) */
	unsigned rsv1 : 5;        // reserved(should be zero I guess)
	/* 예약 필드(0이어야 함) */
	unsigned type : 4;        // type(STS_{TG,IG32,TG32})
	/* 게이트 타입(트랩/인터럽트 등) */
	unsigned s : 1;           // must be 0 (system)
	/* 시스템 비트, 0이어야 함(시스템 게이트) */
	unsigned dpl : 2;         // descriptor(meaning new) privilege level
	/* 디스크립터 권한 레벨(DPL) */
	unsigned p : 1;           // Present
	/* 존재 비트(Present) */
	unsigned off_31_16 : 16;  // high bits of offset in segment
	/* 세그먼트 내 오프셋 상위 16~31비트 */
	uint32_t off_32_63;
	/* 오프셋 32~63비트 */
	uint32_t rsv2;
	/* 예약 필드 */
};

/* The Interrupt Descriptor Table (IDT).  The format is fixed by
   the CPU.  See [IA32-v3a] sections 5.10 "Interrupt Descriptor
   Table (IDT)", 5.11 "IDT Descriptors", 5.12.1.2 "Flag Usage By
   Exception- or Interrupt-Handler Procedure". */
/* 인터럽트 디스크립터 테이블(IDT). 형식은 CPU에 의해 고정된다.
   자세한 내용은 [IA32-v3a] 5.10 "Interrupt Descriptor Table (IDT)",
   5.11 "IDT Descriptors", 5.12.1.2 "Flag Usage By Exception- or
   Interrupt-Handler Procedure" 참고. */
static struct gate idt[INTR_CNT];

static struct desc_ptr idt_desc = {
	.size = sizeof(idt) - 1,
	.address = (uint64_t) idt
};


#define make_gate(g, function, d, t) \
{ \
	ASSERT ((function) != NULL); \
	ASSERT ((d) >= 0 && (d) <= 3); \
	ASSERT ((t) >= 0 && (t) <= 15); \
	*(g) = (struct gate) { \
		.off_15_0 = (uint64_t) (function) & 0xffff, \
		.ss = SEL_KCSEG, \
		.ist = 0, \
		.rsv1 = 0, \
		.type = (t), \
		.s = 0, \
		.dpl = (d), \
		.p = 1, \
		.off_31_16 = ((uint64_t) (function) >> 16) & 0xffff, \
		.off_32_63 = ((uint64_t) (function) >> 32) & 0xffffffff, \
		.rsv2 = 0, \
	}; \
}

/* Creates an interrupt gate that invokes FUNCTION with the given DPL. */
/* 주어진 DPL로 FUNCTION을 호출하는 인터럽트 게이트를 생성한다. */
#define make_intr_gate(g, function, dpl) make_gate((g), (function), (dpl), 14)

/* Creates a trap gate that invokes FUNCTION with the given DPL. */
/* 주어진 DPL로 FUNCTION을 호출하는 트랩 게이트를 생성한다. */
#define make_trap_gate(g, function, dpl) make_gate((g), (function), (dpl), 15)



/* Interrupt handler functions for each interrupt. */
/* 각 인터럽트 번호별 핸들러 함수 테이블. */
static intr_handler_func *intr_handlers[INTR_CNT];

/* Names for each interrupt, for debugging purposes. */
/* 디버깅용 인터럽트 명칭 테이블. */
static const char *intr_names[INTR_CNT];

/* External interrupts are those generated by devices outside the
   CPU, such as the timer.  External interrupts run with
   interrupts turned off, so they never nest, nor are they ever
   pre-empted.  Handlers for external interrupts also may not
   sleep, although they may invoke intr_yield_on_return() to
   request that a new process be scheduled just before the
   interrupt returns. */
/* 외부 인터럽트는 타이머와 같은 CPU 외부 장치가 발생시키는 인터럽트다.
   외부 인터럽트는 인터럽트 비활성 상태에서 실행되므로 중첩되지도,
   선점되지도 않는다. 외부 인터럽트 핸들러는 수면할 수 없지만,
   intr_yield_on_return()을 호출하여 인터럽트 복귀 직전에 새 프로세스를
   스케줄하도록 요청할 수는 있다. */
static bool in_external_intr;   /* Are we processing an external interrupt? */
/* 현재 외부 인터럽트를 처리 중인가? */
static bool yield_on_return;    /* Should we yield on interrupt return? */
/* 인터럽트 복귀 시 양보해야 하는가? */

/* Programmable Interrupt Controller helpers. */
/* 프로그래머블 인터럽트 컨트롤러(PIC) 관련 헬퍼. */
static void pic_init (void);
static void pic_end_of_interrupt (int irq);

/* Interrupt handlers. */
/* 인터럽트 핸들러(공용 진입점). */
void intr_handler (struct intr_frame *args);

/* Returns the current interrupt status. */
/* 현재 인터럽트 상태를 반환한다. */
enum intr_level
intr_get_level (void) {
	uint64_t flags;

	/* Push the flags register on the processor stack, then pop the
	   value off the stack into `flags'.  See [IA32-v2b] "PUSHF"
	   and "POP" and [IA32-v3a] 5.8.1 "Masking Maskable Hardware
	   Interrupts". */
	/* 플래그 레지스터를 스택에 push한 뒤 pop하여 `flags`에 담는다.
	   자세한 내용은 [IA32-v2b] "PUSHF", "POP" 및 [IA32-v3a] 5.8.1
	   "Masking Maskable Hardware Interrupts" 참고. */
	asm volatile ("pushfq; popq %0" : "=g" (flags));

	return flags & FLAG_IF ? INTR_ON : INTR_OFF;
}

/* Enables or disables interrupts as specified by LEVEL and
   returns the previous interrupt status. */
/* LEVEL에 따라 인터럽트를 활성/비활성화하고, 이전 인터럽트 상태를 반환한다. */
enum intr_level
intr_set_level (enum intr_level level) {
	return level == INTR_ON ? intr_enable () : intr_disable ();
}

/* Enables interrupts and returns the previous interrupt status. */
/* 인터럽트를 활성화하고, 이전 인터럽트 상태를 반환한다. */
enum intr_level
intr_enable (void) {
	enum intr_level old_level = intr_get_level ();
	ASSERT (!intr_context ());

	/* Enable interrupts by setting the interrupt flag.

	   See [IA32-v2b] "STI" and [IA32-v3a] 5.8.1 "Masking Maskable
	   Hardware Interrupts". */
	/* 인터럽트 플래그를 세워 인터럽트를 활성화한다.
	   [IA32-v2b] "STI", [IA32-v3a] 5.8.1 참고. */
	asm volatile ("sti");

	return old_level;
}

/* Disables interrupts and returns the previous interrupt status. */
/* 인터럽트를 비활성화하고, 이전 인터럽트 상태를 반환한다. */
enum intr_level
intr_disable (void) {
	enum intr_level old_level = intr_get_level ();

	/* Disable interrupts by clearing the interrupt flag.
	   See [IA32-v2b] "CLI" and [IA32-v3a] 5.8.1 "Masking Maskable
	   Hardware Interrupts". */
	/* 인터럽트 플래그를 내리고 인터럽트를 비활성화한다.
	   [IA32-v2b] "CLI", [IA32-v3a] 5.8.1 참고. */
	asm volatile ("cli" : : : "memory");

	return old_level;
}

/* Initializes the interrupt system. */
/* 인터럽트 시스템을 초기화한다. */
void
intr_init (void) {
	int i;

	/* Initialize interrupt controller. */
	/* 인터럽트 컨트롤러(PIC) 초기화 */
	pic_init ();

	/* Initialize IDT. */
	/* IDT 초기화 */
	for (i = 0; i < INTR_CNT; i++) {
		make_intr_gate(&idt[i], intr_stubs[i], 0);
		intr_names[i] = "unknown";
	}

#ifdef USERPROG
	/* Load TSS. */
	/* TSS 로드 */
	ltr (SEL_TSS);
#endif

	/* Load IDT register. */
	/* IDT 레지스터 로드 */
	lidt(&idt_desc);

	/* Initialize intr_names. */
	/* intr_names 테이블 초기화 */
	intr_names[0] = "#DE Divide Error";
	intr_names[1] = "#DB Debug Exception";
	intr_names[2] = "NMI Interrupt";
	intr_names[3] = "#BP Breakpoint Exception";
	intr_names[4] = "#OF Overflow Exception";
	intr_names[5] = "#BR BOUND Range Exceeded Exception";
	intr_names[6] = "#UD Invalid Opcode Exception";
	intr_names[7] = "#NM Device Not Available Exception";
	intr_names[8] = "#DF Double Fault Exception";
	intr_names[9] = "Coprocessor Segment Overrun";
	intr_names[10] = "#TS Invalid TSS Exception";
	intr_names[11] = "#NP Segment Not Present";
	intr_names[12] = "#SS Stack Fault Exception";
	intr_names[13] = "#GP General Protection Exception";
	intr_names[14] = "#PF Page-Fault Exception";
	intr_names[16] = "#MF x87 FPU Floating-Point Error";
	intr_names[17] = "#AC Alignment Check Exception";
	intr_names[18] = "#MC Machine-Check Exception";
	intr_names[19] = "#XF SIMD Floating-Point Exception";
}

/* Registers interrupt VEC_NO to invoke HANDLER with descriptor
   privilege level DPL.  Names the interrupt NAME for debugging
   purposes.  The interrupt handler will be invoked with
   interrupt status set to LEVEL. */
/* 인터럽트 벡터 VEC_NO에 대해, DPL 권한으로 HANDLER를 등록한다.
   디버깅을 위해 인터럽트 이름을 NAME으로 설정한다.
   인터럽트가 발생하면, 인터럽트 상태 LEVEL로 핸들러가 호출된다. */
static void
register_handler (uint8_t vec_no, int dpl, enum intr_level level,
		intr_handler_func *handler, const char *name) {
	ASSERT (intr_handlers[vec_no] == NULL);
	if (level == INTR_ON) {
		make_trap_gate(&idt[vec_no], intr_stubs[vec_no], dpl);
	}
	else {
		make_intr_gate(&idt[vec_no], intr_stubs[vec_no], dpl);
	}
	intr_handlers[vec_no] = handler;
	intr_names[vec_no] = name;
}

/* Registers external interrupt VEC_NO to invoke HANDLER, which
   is named NAME for debugging purposes.  The handler will
   execute with interrupts disabled. */
/* 외부 인터럽트 VEC_NO에 대해 HANDLER를 등록한다(디버깅용 이름은 NAME).
   이 핸들러는 인터럽트 비활성 상태에서 실행된다. */
void
intr_register_ext (uint8_t vec_no, intr_handler_func *handler,
		const char *name) {
	ASSERT (vec_no >= 0x20 && vec_no <= 0x2f);
	register_handler (vec_no, 0, INTR_OFF, handler, name);
}

/* Registers internal interrupt VEC_NO to invoke HANDLER, which
   is named NAME for debugging purposes.  The interrupt handler
   will be invoked with interrupt status LEVEL.

   The handler will have descriptor privilege level DPL, meaning
   that it can be invoked intentionally when the processor is in
   the DPL or lower-numbered ring.  In practice, DPL==3 allows
   user mode to invoke the interrupts and DPL==0 prevents such
   invocation.  Faults and exceptions that occur in user mode
   still cause interrupts with DPL==0 to be invoked.  See
   [IA32-v3a] sections 4.5 "Privilege Levels" and 4.8.1.1
   "Accessing Nonconforming Code Segments" for further
   discussion. */
/* 내부 인터럽트 VEC_NO에 대해 HANDLER를 등록한다(디버깅용 이름은 NAME).
   인터럽트는 LEVEL 상태에서 핸들러가 호출된다.

   핸들러는 DPL 권한을 가지며, CPU가 해당 DPL 또는 더 낮은 링일 때 의도적으로
   호출될 수 있다. 실제로 DPL==3이면 유저 모드에서 호출 가능하고, DPL==0이면
   그러한 호출을 막는다. 단, 유저 모드에서 발생한 fault/exception은 여전히
   DPL==0 인터럽트를 통해 처리된다. 자세한 내용은 [IA32-v3a] 4.5 "Privilege Levels",
   4.8.1.1 "Accessing Nonconforming Code Segments" 참고. */
void
intr_register_int (uint8_t vec_no, int dpl, enum intr_level level,
		intr_handler_func *handler, const char *name)
{
	ASSERT (vec_no < 0x20 || vec_no > 0x2f);
	register_handler (vec_no, dpl, level, handler, name);
}

/* Returns true during processing of an external interrupt
   and false at all other times. */
/* 외부 인터럽트를 처리 중이면 true, 아니면 false를 반환한다. */
bool
intr_context (void) {
	return in_external_intr;
}

/* During processing of an external interrupt, directs the
   interrupt handler to yield to a new process just before
   returning from the interrupt.  May not be called at any other
   time. */
/* 외부 인터럽트 처리 중에만 사용. 인터럽트로부터 복귀 직전에
   스케줄러가 다른 프로세스로 양보(yield)하도록 지시한다.
   다른 시점에는 호출할 수 없다. */
void
intr_yield_on_return (void) {
	ASSERT (intr_context ());
	yield_on_return = true;
}

/* 8259A Programmable Interrupt Controller. */
/* 8259A 프로그래머블 인터럽트 컨트롤러(PIC). */

/* Every PC has two 8259A Programmable Interrupt Controller (PIC)
   chips.  One is a "master" accessible at ports 0x20 and 0x21.
   The other is a "slave" cascaded onto the master's IRQ 2 line
   and accessible at ports 0xa0 and 0xa1.  Accesses to port 0x20
   set the A0 line to 0 and accesses to 0x21 set the A1 line to
   1.  The situation is similar for the slave PIC.

   By default, interrupts 0...15 delivered by the PICs will go to
   interrupt vectors 0...15.  Unfortunately, those vectors are
   also used for CPU traps and exceptions.  We reprogram the PICs
   so that interrupts 0...15 are delivered to interrupt vectors
   32...47 (0x20...0x2f) instead. */
/* 일반적인 PC에는 두 개의 8259A PIC가 있다.
   하나는 "마스터"로 포트 0x20, 0x21에서 접근 가능하고,
   다른 하나는 마스터의 IRQ2 라인에 연결된 "슬레이브"로
   포트 0xa0, 0xa1에서 접근 가능하다. 0x20 접근은 A0 라인을 0으로,
   0x21 접근은 A1 라인을 1로 설정한다. 슬레이브 PIC도 유사하다.

   기본적으로 PIC가 전달하는 인터럽트 0..15는 인터럽트 벡터 0..15로 간다.
   하지만 이 벡터들은 CPU 트랩/예외에서도 사용되므로, 충돌을 피하기 위해
   PIC를 재프로그램하여 인터럽트 0..15가 벡터 32..47(0x20..0x2f)로 가도록 한다. */

/* Initializes the PICs.  Refer to [8259A] for details. */
/* PIC를 초기화한다. 자세한 내용은 [8259A] 문서 참고. */
static void
pic_init (void) {
	/* Mask all interrupts on both PICs. */
	/* 두 PIC의 모든 인터럽트를 마스킹(비활성화) */
	outb (0x21, 0xff);
	outb (0xa1, 0xff);

	/* Initialize master. */
	/* 마스터 PIC 초기화 */
	outb (0x20, 0x11); /* ICW1: single mode, edge triggered, expect ICW4. */
	/* ICW1: 단일 모드, 에지 트리거, ICW4 기대 */
	outb (0x21, 0x20); /* ICW2: line IR0...7 -> irq 0x20...0x27. */
	/* ICW2: IR0..7을 irq 0x20..0x27로 매핑 */
	outb (0x21, 0x04); /* ICW3: slave PIC on line IR2. */
	/* ICW3: 슬레이브 PIC는 IR2에 연결 */
	outb (0x21, 0x01); /* ICW4: 8086 mode, normal EOI, non-buffered. */
	/* ICW4: 8086 모드, 일반 EOI, 비버퍼 방식 */

	/* Initialize slave. */
	/* 슬레이브 PIC 초기화 */
	outb (0xa0, 0x11); /* ICW1: single mode, edge triggered, expect ICW4. */
	/* ICW1: 단일 모드, 에지 트리거, ICW4 기대 */
	outb (0xa1, 0x28); /* ICW2: line IR0...7 -> irq 0x28...0x2f. */
	/* ICW2: IR0..7을 irq 0x28..0x2f로 매핑 */
	outb (0xa1, 0x02); /* ICW3: slave ID is 2. */
	/* ICW3: 슬레이브 ID는 2 */
	outb (0xa1, 0x01); /* ICW4: 8086 mode, normal EOI, non-buffered. */
	/* ICW4: 8086 모드, 일반 EOI, 비버퍼 방식 */

	/* Unmask all interrupts. */
	/* 모든 인터럽트 언마스킹(활성화) */
	outb (0x21, 0x00);
	outb (0xa1, 0x00);
}

/* Sends an end-of-interrupt signal to the PIC for the given IRQ.
   If we don't acknowledge the IRQ, it will never be delivered to
   us again, so this is important.  */
/* 주어진 IRQ에 대해 PIC로 EOI(End Of Interrupt) 신호를 보낸다.
   이를 확인(ack)하지 않으면 이후 해당 IRQ가 다시 전달되지 않으므로 중요하다. */
static void
pic_end_of_interrupt (int irq) {
	ASSERT (irq >= 0x20 && irq < 0x30);

	/* Acknowledge master PIC. */
	/* 마스터 PIC에 EOI 전송 */
	outb (0x20, 0x20);

	/* Acknowledge slave PIC if this is a slave interrupt. */
	/* 슬레이브 인터럽트라면 슬레이브 PIC에도 EOI 전송 */
	if (irq >= 0x28)
		outb (0xa0, 0x20);
}
/* Interrupt handlers. */
/* 인터럽트 핸들러들. */

/* Handler for all interrupts, faults, and exceptions.  This
   function is called by the assembly language interrupt stubs in
   intr-stubs.S.  FRAME describes the interrupt and the
   interrupted thread's registers. */
/* 모든 인터럽트/폴트/예외의 공용 핸들러.
   이 함수는 intr-stubs.S의 어셈블리 스텁에 의해 호출된다.
   FRAME에는 인터럽트 정보와 인터럽트된 스레드의 레지스터 상태가 담긴다. */
void
intr_handler (struct intr_frame *frame) {
	bool external;
	intr_handler_func *handler;

	/* External interrupts are special.
	   We only handle one at a time (so interrupts must be off)
	   and they need to be acknowledged on the PIC (see below).
	   An external interrupt handler cannot sleep. */
	/* 외부 인터럽트는 특별 취급된다.
	   한 번에 하나만 처리하며(따라서 인터럽트는 비활성 상태),
	   PIC에 대한 확인(ack)이 필요하다(아래 참고).
	   외부 인터럽트 핸들러는 수면할 수 없다. */
	external = frame->vec_no >= 0x20 && frame->vec_no < 0x30;
	if (external) {
		ASSERT (intr_get_level () == INTR_OFF);
		ASSERT (!intr_context ());

		in_external_intr = true;
		yield_on_return = false;
	}

	/* Invoke the interrupt's handler. */
	/* 해당 인터럽트의 핸들러를 호출 */
	handler = intr_handlers[frame->vec_no];
	if (handler != NULL)
		handler (frame);
	else if (frame->vec_no == 0x27 || frame->vec_no == 0x2f) {
		/* There is no handler, but this interrupt can trigger
		   spuriously due to a hardware fault or hardware race
		   condition.  Ignore it. */
		/* 핸들러는 없지만, 하드웨어 결함/레이스로 인해 가끔 발생할 수 있는
		   가짜(spurious) 인터럽트이므로 무시한다. */
	} else {
		/* No handler and not spurious.  Invoke the unexpected
		   interrupt handler. */
		/* 핸들러가 없고 가짜도 아니다. 예기치 않은 인터럽트로 처리. */
		intr_dump_frame (frame);
		PANIC ("Unexpected interrupt");
	}

	/* Complete the processing of an external interrupt. */
	/* 외부 인터럽트 처리 마무리 */
	if (external) {
		ASSERT (intr_get_level () == INTR_OFF);
		ASSERT (intr_context ());

		in_external_intr = false;
		pic_end_of_interrupt (frame->vec_no);

		if (yield_on_return)
			thread_yield ();
	}
}

/* Dumps interrupt frame F to the console, for debugging. */
/* 디버깅을 위해 인터럽트 프레임 F를 콘솔에 덤프한다. */
void
intr_dump_frame (const struct intr_frame *f) {
	/* CR2 is the linear address of the last page fault.
	   See [IA32-v2a] "MOV--Move to/from Control Registers" and
	   [IA32-v3a] 5.14 "Interrupt 14--Page Fault Exception
	   (#PF)". */
	/* CR2는 마지막 페이지 폴트가 발생한 선형 주소를 담는다.
	   [IA32-v2a] "MOV--Move to/from Control Registers",
	   [IA32-v3a] 5.14 "Interrupt 14--Page Fault Exception(#PF)" 참고. */
	uint64_t cr2 = rcr2();
	printf ("Interrupt %#04llx (%s) at rip=%llx\n",
			f->vec_no, intr_names[f->vec_no], f->rip);
	printf (" cr2=%016llx error=%16llx\n", cr2, f->error_code);
	printf ("rax %016llx rbx %016llx rcx %016llx rdx %016llx\n",
			f->R.rax, f->R.rbx, f->R.rcx, f->R.rdx);
	printf ("rsp %016llx rbp %016llx rsi %016llx rdi %016llx\n",
			f->rsp, f->R.rbp, f->R.rsi, f->R.rdi);
	printf ("rip %016llx r8 %016llx  r9 %016llx r10 %016llx\n",
			f->rip, f->R.r8, f->R.r9, f->R.r10);
	printf ("r11 %016llx r12 %016llx r13 %016llx r14 %016llx\n",
			f->R.r11, f->R.r12, f->R.r13, f->R.r14);
	printf ("r15 %016llx rflags %08llx\n", f->R.r15, f->eflags);
	printf ("es: %04x ds: %04x cs: %04x ss: %04x\n",
			f->es, f->ds, f->cs, f->ss);
}

/* Returns the name of interrupt VEC. */
/* 인터럽트 VEC의 이름을 반환한다. */
const char *
intr_name (uint8_t vec) {
	return intr_names[vec];
}
